[build]
  base = "site/"
  command = "hugo --gc --minify"
  publish = "site/public"

[context.production.environment]
  HUGO_VERSION = "0.81.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.81.0"
