# Site settings
title: Sonobuoy
email:
author: Sonobuoy Authors
description:
url:
logo: Sonobuoy.svg
vm_logo: vm-logo.png
gh_repo: https://github.com/heptio/sonobuoy
markdown: redcarpet
hero:
  background-color: med-blue
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title:
  cta_url: /docs/v0.14.3
  cta_text: Documentation
  vm-link: http://vmware.github.io/

footer_social_links:
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/projectsonobuoy
  Slack:
    fa_icon: fab fa-slack
    url: https://kubernetes.slack.com/messages/sonobuoy
  RSS:
    fa_icon: fa fa-rss
    url: feed.xml
  GitHub:
    fa_icon: fab fa-github
    url: https://github.com/heptio/sonobuoy

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: docs/master
    values:
      version: master
      gh: https://github.com/heptio/sonobuoy/tree/master
      layout: "docs"
  - scope:
      path: docs/v0.14.3
    values:
      version: v0.14.3
      gh: https:/github.com/heptio/sonobuoy/tree/v0.14.3
      layout: "docs"
  - scope:
      path: docs/v0.14.2
    values:
      version: v0.14.2
      gh: https:/github.com/heptio/sonobuoy/tree/v0.14.2
      layout: "docs"
  - scope:
      path: docs/v0.14.1
    values:
      version: v0.14.1
      gh: https:/github.com/heptio/sonobuoy/tree/v0.14.1
      layout: "docs"
  - scope:
      path: docs/v0.14.0
    values:
      version: v0.14.0
      gh: https:/github.com/heptio/sonobuoy/tree/v0.14.0
      layout: "docs"
  - scope:
      path: docs/v0.13.0
    values:
      version: v0.13.0
      gh: https:/github.com/heptio/sonobuoy/tree/v0.13.0
      layout: "docs"

collections:
  - contributors
  - casestudies

versioning: true
latest: v0.14.3
versions:
- master
- v0.14.3
- v0.14.2
- v0.14.1
- v0.14.0
- v0.13.0

# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)


# Include these subdirectories
include:
  - CONTRIBUTING.md
  - README.md

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - LICENSE
  - CNAME
  - Runbook.docx
  - '*.sh'

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
