---
apiVersion: v1
kind: Namespace
metadata:
  name: heptio-sonobuoy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonobuoy-serviceaccount
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
  namespace: heptio-sonobuoy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
data:
  config.json: |
    {
        "Description": "EXAMPLE",
        "Filters": {
            "LabelSelector": "",
            "Namespaces": ".*"
        },
        "PluginNamespace": "heptio-sonobuoy",
        "Plugins": [
            {
                "name": "systemd_logs"
            },
            {
                "name": "e2e"
            }
        ],
        "Resources": [
            "CertificateSigningRequests",
            "ClusterRoleBindings",
            "ClusterRoles",
            "ComponentStatuses",
            "CustomResourceDefinitions",
            "Nodes",
            "PersistentVolumes",
            "PodSecurityPolicies",
            "ServerVersion",
            "StorageClasses",
            "ConfigMaps",
            "DaemonSets",
            "Deployments",
            "Endpoints",
            "Events",
            "HorizontalPodAutoscalers",
            "Ingresses",
            "Jobs",
            "LimitRanges",
            "PersistentVolumeClaims",
            "Pods",
            "PodDisruptionBudgets",
            "PodTemplates",
            "ReplicaSets",
            "ReplicationControllers",
            "ResourceQuotas",
            "RoleBindings",
            "Roles",
            "ServerGroups",
            "ServiceAccounts",
            "Services",
            "StatefulSets"
        ],
        "ResultsDir": "/tmp/sonobuoy",
        "Server": {
            "advertiseaddress": "sonobuoy-master:8080",
            "bindaddress": "0.0.0.0",
            "bindport": 8080,
            "timeoutseconds": 5400
        },
        "Version": "v0.9.0"
    }
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: heptio-sonobuoy
---
apiVersion: v1
data:
  e2e.tmpl: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: "sonobuoy-e2e-job-{{.SessionID}}"
      annotations:
        "sonobuoy-plugin": "e2e"
        "sonobuoy-driver": "Job"
        "sonobuoy-result-type": "e2e"
      labels:
        component: sonobuoy
      tier: analysis
      "sonobuoy-run": "{{.SessionID}}"
      namespace: "{{.Namespace}}"
    spec:
      serviceAccountName: sonobuoy-serviceaccount
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      restartPolicy: Never
      containers:
      - name: e2e
        image: gcr.io/heptio-images/kube-conformance:latest
        imagePullPolicy: Always
        # NOTE: Full conformance can take a while depending on your cluster size.
        # As a result, only a single test is set atm to verify correctness.
        # Operators that want the complete test results can comment out the
        # env section.
        env:
        - name: E2E_FOCUS
          value: "Pods should be submitted and removed"
        volumeMounts:
        - name: results
          mountPath: /tmp/results
      - name: sonobuoy-worker
        command:
        - sh
        - -c
        - /sonobuoy worker global -v 5 --logtostderr
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: RESULTS_DIR
          value: /tmp/results
        - name: MASTER_URL
          value: "{{.MasterAddress}}"
        - name: RESULT_TYPE
          value: "e2e"
        image: gcr.io/heptio-images/sonobuoy:master
        imagePullPolicy: Always
        volumeMounts:
        - name: results
          mountPath: /tmp/results
      volumes:
      - name: results
        emptyDir: {}
  systemd_logs.tmpl: |
    apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      name: "sonobuoy-systemd-logs-config-{{.SessionID}}"
      annotations:
        "sonobuoy-plugin": "systemd_logs"
        "sonobuoy-driver": "DaemonSet"
        "sonobuoy-result-type": "systemd_logs"
      labels:
        component: sonobuoy
        tier: analysis
        "sonobuoy-run": "{{.SessionID}}"
      namespace: {{.Namespace}}
    spec:
      selector:
        matchLabels:
          "sonobuoy-run": "{{.SessionID}}"
      template:
        metadata:
          labels:
            component: sonobuoy
            tier: analysis
            "sonobuoy-run": "{{.SessionID}}"
        spec:
          tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: CriticalAddonsOnly
            operator: Exists
          hostNetwork: true
          hostIPC: true
          hostPID: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
          - name: systemd-logs
            command:
            - sh
            - -c
            - /get_systemd_logs.sh && sleep 3600
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: RESULTS_DIR
              value: /tmp/results
            - name: CHROOT_DIR
              value: /node
            image: gcr.io/heptio-images/sonobuoy-plugin-systemd-logs:latest
            imagePullPolicy: Always
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /node
              name: root
            - mountPath: /tmp/results
              name: results
          - name: sonobuoy-worker
            command:
            - sh
            - -c
            - /sonobuoy worker single-node -v 5 --logtostderr && sleep 3600
            env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: RESULTS_DIR
              value: /tmp/results
            - name: MASTER_URL
              value: "{{.MasterAddress}}"
            image: gcr.io/heptio-images/sonobuoy:master
            imagePullPolicy: Always
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /tmp/results
              name: results
          volumes:
          - name: root
            hostPath:
              path: /
          - name: results
            emptyDir: {}

kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: heptio-sonobuoy
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: sonobuoy
    run: sonobuoy-master
    tier: analysis
  name: sonobuoy
  namespace: heptio-sonobuoy
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - /sonobuoy master --no-exit=true -v 3 --logtostderr
    env:
    - name: SONOBUOY_ADVERTISE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    image: gcr.io/heptio-images/sonobuoy:master
    imagePullPolicy: Always
    name: kube-sonobuoy
    volumeMounts:
    - mountPath: /etc/sonobuoy
      name: sonobuoy-config-volume
    - mountPath: /plugins.d
      name: sonobuoy-plugins-volume
    - mountPath: /tmp/sonobuoy
      name: output-volume
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
  volumes:
  - configMap:
      name: sonobuoy-config-cm
    name: sonobuoy-config-volume
  - configMap:
      name: sonobuoy-plugins-cm
    name: sonobuoy-plugins-volume
  - emptyDir: {}
    name: output-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: sonobuoy
    run: sonobuoy-master
  name: sonobuoy-master
  namespace: heptio-sonobuoy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: sonobuoy-master
  type: ClusterIP
