name: CD Release
on:
  push:
    branches:
      - master
  pull:
    branches:
      - master
jobs:
  publish-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: make publish_containers
        env:
          VERBOSE: true
          KO_DOCKER_REPO: docker.io/sonobuoy
        run: |
          make publish_containers
