name: CI Test
on: [push, pull_request]
jobs:
  unit-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run unit tests
        env:
          VERBOSE: true
        run: |
          source ./scripts/build.sh; unit_local
  stress-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run stress tests
        env:
          VERBOSE: true
        run: |
          source ./scripts/build.sh; stress
  integration-test-on-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          source ./scripts/build.sh; prepare_and_run_integration
