name: CI Test
on: [push, pull_request]
jobs:
  unit-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: make local-test
        env:
          VERBOSE: true
        run: |
          make local-test
  stress-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make stress-test
        env:
          VERBOSE: true
        run: |
          make stress
  integration-test-on-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run tests
        run: |
          curl -L https://github.com/google/ko/releases/download/v0.8.0/ko_0.8.0_Linux_x86_64.tar.gz | tar xzf - ko
          sudo mv ko /usr/local/bin/
          ./scripts/run_integration_tests.sh
